[project]
name = "portfolioblog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "3-10",
    "django>=5.1.3",
    "python",
]
